#!/bin/sh
protected_branch='dev'  
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

DIR=$(dirname "$0")

exec java $DIR/HookPrePush.java $protected_branch $current_branch
# if [ $protected_branch = $current_branch ]  
# then  
  
#     echo -en "\033[31mTu es sur le point de push sur le dev, est-ce que tu veux vraiment ? [y|n] \033[0m"
#     echo -en "\033[1m"
#     read -n 1 -r < /dev/tty
#     echo -en "\033[0m"
    
#     echo
#     if echo $REPLY | grep -E '^[Yy]$' > /dev/null
#     then
#         exit 0 # push will execute
#     fi
#     exit 1 # push will not execute
# else  
#     exit 0 # push will execute
# fi 